---
title: "dunnart_DMRs"
output: pdf_document
date: '2025-08-02'
---
```{r}
library(data.table)
library(GenomicRanges)
library(DMRcate)
library(bsseq)
library(plyr)
library(limma)
library(ggplot2)
```

###---load in bedgraphs
```{r}
setwd("/Users/ksenia/Documents/Lab_Garvan/projects/marsupials/EMseq_final_genome/mapping/bedGraph/")
bedgraphs <- list.files()
ids <- gsub("_R1_paired_sorted_dedup_sorted_filter.svg_CpG.bedGraph", "", bedgraphs)

samples <- list()

setwd("/Users/ksenia/Documents/Lab_Garvan/projects/marsupials/EMseq_final_genome/mapping/bedGraph/")
for (i in bedgraphs){
  
  tab <- fread(i)
  #Adding +1 to the start position for cytosines, assuming zero-based bedGraph
  tab <-  GRanges(tab[[1]], IRanges(tab[[2]] + 1, width=1), C=tab[[5]], cov=tab[[5]]+tab[[6]])
  samples <- c(samples, tab)
  print(i)
}

bigtable <- Reduce(GenomicRanges::union, samples)

for(i in 1:length(samples)){
  m <- match(samples[[i]], bigtable)
  c <- rep(0, length(bigtable))
  c[m] <- samples[[i]]$C
  elementMetadata(bigtable)[paste0(ids[i], ".C")] <- c
  cov <- rep(0, length(bigtable))
  cov[m] <- samples[[i]]$cov
  elementMetadata(bigtable)[paste0(ids[i], ".cov")] <- cov
  message(i)
}


```


###---Remove scaffolds with only 1 CpG
```{r}
chromcounts <- table(seqnames(bigtable))
singletons <- names(chromcounts)[chromcounts==1]
bigtable <- bigtable[!seqnames(bigtable) %in% singletons]

#save(bigtable, file="dunnart_bigtable.RData")

colnames(mcols(bigtable)) <- gsub("dunnart_", "", colnames(mcols(bigtable)))

meta <- data.frame(ID=gsub("dunnart_", "", ids))
meta$C <- paste0(meta$ID, ".C")
meta$cov <- paste0(meta$ID, ".cov")
meta$timepoint <- gsub("_.*", "", meta$ID) #removes the rep1/rep2

meta$col <- as.character(mapvalues(meta$timepoint, 
                                      c("sperm","d9", "d10", "d12", "d13", "liver"), 
                                      c("black","blue", "deepskyblue", "coral", "red", "maroon")))
rownames(meta) <- meta$ID

#               ID          C          cov timepoint         col
#d10_r1     d10_r1   d10_r1.C   d10_r1.cov       d10 deepskyblue
#d10_r2     d10_r2   d10_r2.C   d10_r2.cov       d10 deepskyblue
#d12_r1     d12_r1   d12_r1.C   d12_r1.cov       d12       coral
#d12_r2     d12_r2   d12_r2.C   d12_r2.cov       d12       coral
#d13_r1     d13_r1   d13_r1.C   d13_r1.cov       d13         red
#d13_r2     d13_r2   d13_r2.C   d13_r2.cov       d13         red
#d9_r1       d9_r1    d9_r1.C    d9_r1.cov        d9        blue
#d9_r2       d9_r2    d9_r2.C    d9_r2.cov        d9        blue
#liver_r1 liver_r1 liver_r1.C liver_r1.cov     liver      maroon
#liver_r2 liver_r2 liver_r2.C liver_r2.cov     liver      maroon
#sperm_r1 sperm_r1 sperm_r1.C sperm_r1.cov     sperm       black
#sperm_r2 sperm_r2 sperm_r2.C sperm_r2.cov     sperm       black


#keep <- rowSums(as.matrix(values(tmp[,grep("cov$", colnames(values(tmp)))]))) > 0
#bigtable <- tmp[keep]

coverage <- values(bigtable[,meta$cov])
numcovered <- apply(coverage, 2, function (x) sum(x != 0))
pccovered <- numcovered*100/length(bigtable)
```



###---DMRs
###---Create BSSeq object for DMRcate
```{r}
coverage <- as.matrix(values(bigtable[,meta$cov]))
meth <- as.matrix(values(bigtable[,meta$C]))
colnames(coverage) <- colnames(meth) <- meta$ID

bsseq_data <- BSseq(chr = seqnames(bigtable), pos = start(bigtable), M = meth, Cov = coverage, sampleNames = meta$ID)
pData(bsseq_data) <- meta

timepoint <- meta$timepoint
design <- model.matrix(~0 + timepoint)
colnames(design) <- gsub("timepoint", "", colnames(design))
methdesign <- edgeR::modelMatrixMeth(design)
cont.mat <- makeContrasts(d9vssperm=d9-sperm,
                          d10vsd9=d10-d9,
                          d12vsd10=d12-d10,
                          d13vsd12=d13-d12,
                          livervsd13=liver-d13,
                          levels=methdesign)

```



###---DMC Analysis: Sperm vs Day 9
```{r}
library(DMRcate)
library(ggplot2)

# Identify DMCs
seq_annot <- sequencing.annotate(bsseq_data, methdesign, all.cov = TRUE,
                                contrasts = TRUE, cont.matrix = cont.mat,
                                coef = "d9vssperm", fdr = 0.05)
dmrcate.res <- dmrcate(seq_annot, C = 2, min.cpgs = 1)


# Extract all CpGs:
gr <- seq_annot@ranges
# Extract significant DMCs
gr_sig <- seq_annot@ranges[seq_annot@ranges$is.sig == "TRUE"]

# Calculate methylation scores
CpG <- c(bigtable, ignore.mcols=TRUE)
values(CpG) <- as.data.frame(bigtable)[,-c(1:5)]  

col<-seq(1, ncol(mcols(CpG)), by=2)
names <- sub("\\.(C|cov)$", "", colnames(mcols(CpG))[col])
col <- setNames(col, names)


mc_score <- mapply(function(a, b){mcols(CpG)[, a] / mcols(CpG)[, b]}, a = col, b = col+1) 
mc_score<-as.data.frame(mc_score)
mcols(CpG) <- NULL
mcols(CpG) <- cbind(mcols(CpG), mc_score)

# Calculate methylation differences
CpG_sig <- subsetByOverlaps(CpG, gr_sig)
CpG_sig$delta <- (CpG_sig$d9_r1 + CpG_sig$d9_r2)/2 - 
                 (CpG_sig$sperm_r1 + CpG_sig$sperm_r2)/2

# Filter scaffolds and calculate percentages
puc_lambda <- c("pUC19", "chrLambda")
CpG_filt <- CpG_sig[!seqnames(CpG_sig) %in% puc_lambda]
gr_filt <- gr[!seqnames(gr) %in% puc_lambda]
total_cpgs <- length(gr_filt) #total number of CpGs with min cov of 1 in two samples which are being compared - 8122402

# Define diff mC thresholds and calculate percentages
calculate_percentages <- function(data, total, thresholds = c(0.2, 0.5)) {
  results <- list()
  for (thresh in thresholds) {
    hypo <- sum(data$delta <= -thresh) / total * 100
    hyper <- sum(data$delta >= thresh) / total * 100
    results[[paste0(thresh * 100, "per")]] <- c(hypo = hypo, hyper = hyper)
  }
  return(results)
}

percentages <- calculate_percentages(as.data.frame(CpG_filt), total_cpgs)

# Create visualization function
plot_dmc_percentages <- function(hypo_pct, hyper_pct, threshold, filename) {
  df <- data.frame(
    per_of_CpGs = c(hypo_pct, hyper_pct),
    DMC_type = c("Hypomethylated", "Hypermethylated"),
    design = "E9 vs sperm"
  )
  
  p <- ggplot(df, aes(x = design, y = per_of_CpGs, fill = DMC_type)) +
    geom_col(position = "stack") +
    geom_text(aes(label = paste0(round(per_of_CpGs, 2), "%")), 
              position = position_stack(vjust = 0.5), color = "white", fontface = "bold") +
    labs(title = paste0("DMCs (±", threshold, "%)"),
         subtitle = "E9 vs Sperm",
         y = "Percentage of CpGs", x = NULL, fill = "Direction") +
    scale_y_continuous(limits = c(0, 100), labels = function(x) paste0(x, "%")) +
    scale_fill_manual(values = c("Hypomethylated" = "#2166AC", "Hypermethylated" = "#D73027")) +
    theme_minimal() +
    theme(plot.title = element_text(face = "bold", hjust = 0.5),
          plot.subtitle = element_text(hjust = 0.5),
          axis.text.x = element_blank(),
          legend.position = "bottom")
  
  ggsave(filename, p, width = 1.5, height = 5, units = "in", dpi = 300)
  return(p)
}

# Generate plots
setwd("/Users/ksenia/Documents/Lab_Garvan/projects/marsupials/EMseq_final_genome/DMCs_DMRcate/figures/")
p1 <- plot_dmc_percentages(percentages$`20per`["hypo"], percentages$`20per`["hyper"], 
                          20, "DMCs_sperm_vs_E9_20pct_threshold.pdf")
p2 <- plot_dmc_percentages(percentages$`50per`["hypo"], percentages$`50per`["hyper"], 
                          50, "DMCs_sperm_vs_E9_50pct_threshold.pdf")


# Save results
saveRDS(percentages, "/Users/ksenia/Documents/Lab_Garvan/projects/marsupials/EMseq_final_genome/DMCs_DMRcate/source_data/DMC_percentages_sperm_vs_E9.rds")
saveRDS(as.data.frame(CpG_filt), "/Users/ksenia/Documents/Lab_Garvan/projects/marsupials/EMseq_final_genome/DMCs_DMRcate/source_data/DMC_mC_score_sperm_vs_E9_sign.rds")

# Export BED files
setwd("/Users/ksenia/Documents/Lab_Garvan/projects/marsupials/EMseq_final_genome/DMCs_DMRcate/source_data/")
rtracklayer::export(gr_filt, "SpermvsE9_background.bed")
rtracklayer::export(gr_sig, "SpermvsE9_significant_DMCs.bed")
rtracklayer::export(CpG_filt[CpG_filt$delta <= -0.2], "SpermvsE9_hypomethylated_20pct.bed")
rtracklayer::export(CpG_filt[CpG_filt$delta >= 0.2], "SpermvsE9_hypermethylated_20pct.bed")
```


###---DMR Analysis: Sperm vs Day 9

```{r}
d9vssperm.DMRs <- GRanges(dmrcate.res@coord, 
                            values=data.frame(no.cpgs=dmrcate.res@no.cpgs,
                                              min.smoothed.fdr=dmrcate.res@min_smoothed_fdr,
                                              Stouffer=dmrcate.res@Stouffer,
                                              HMFDR=dmrcate.res@HMFDR,
                                              Fisher=dmrcate.res@Fisher,
                                              maxdiff=dmrcate.res@maxdiff,
                                              meandiff=dmrcate.res@meandiff))
colnames(values(d9vssperm.DMRs)) <- gsub("values.", "", colnames(values(d9vssperm.DMRs)))
d9vssperm.DMRs <- d9vssperm.DMRs[d9vssperm.DMRs$no.cpgs >=5 & ICMvssperm.DMRs$min.smoothed.fdr < 0.05,]
write.csv(as.data.frame(d9vssperm.DMRs), file="/Users/ksenia/Documents/Lab_Garvan/projects/marsupials/EMseq_final_genome/DMCs_DMRcate/DMRs/dunnart_d9_vs_sperm.DMRs.csv", row.names = F)
saveRDS(as.data.frame(d9vssperm.DMRs), file="/Users/ksenia/Documents/Lab_Garvan/projects/marsupials/EMseq_final_genome/DMCs_DMRcate/DMRs/dunnart_d9_vs_sperm.DMRs.rds")
```


```{r}

CpG <- c(bigtable, ignore.mcols=TRUE)
values(CpG) <- as.data.frame(bigtable)[,-c(1:5)]  

col<-seq(1, ncol(mcols(CpG)), by=2)
names <- sub("\\.(C|cov)$", "", colnames(mcols(CpG))[col])
col <- setNames(col, names)

d9vssperm.DMRs <- subsetByOverlaps(d9vssperm.DMRs, CpG)

av_meth <- mapply(function(a, b){overlapRatios(CpG, d9vssperm.DMRs, a, b, minCov=1)}, a = col, b = col+1) # calculates methylation ratio using .C and .cov of adjacent columns 
x<- as.data.frame(av_meth)
mcols(d9vssperm.DMRs) <- cbind(mcols(d9vssperm.DMRs), x)
d9vssperm.DMRs$delta_d9_sperm <- (d9vssperm.DMRs$d9_r1 + d9vssperm.DMRs$d9_r2)/2 - (d9vssperm.DMRs$sperm_r1 + d9vssperm.DMRs$sperm_r2)/2


d9vssperm.DMRs$DMR_status <- ifelse(d9vssperm.DMRs$delta_d9_sperm <= -0.3, "d9_hypo", ifelse(d9vssperm.DMRs$delta_d9_sperm >= 0.3, "d9_hyper", "NA"))
table(d9vssperm.DMRs$DMR_status)
saveRDS(as.data.frame(d9vssperm.DMRs), file="/Users/ksenia/Documents/Lab_Garvan/projects/marsupials/EMseq_final_genome/DMCs_DMRcate/DMRs//dunnart_d9_vs_sperm.DMRs_delta.rds")

#d9_hyper  d9_hypo       NA 
#     163   367874    12242 

d9vssperm.DMRs_hypo <- d9vssperm.DMRs[which(d9vssperm.DMRs$DMR_status=="d9_hypo"),]
d9vssperm.DMRs_hyper <- d9vssperm.DMRs[which(d9vssperm.DMRs$DMR_status=="d9_hyper"),]

export(d9vssperm.DMRs_hypo, "/Users/ksenia/Documents/Lab_Garvan/projects/marsupials/EMseq_final_genome/DMCs_DMRcate/DMRs//dunnart_d9_vs_sperm.DMRs_hypo0.3.bed")
export(d9vssperm.DMRs_hyper, "/Users/ksenia/Documents/Lab_Garvan/projects/marsupials/EMseq_final_genome/DMCs_DMRcate/DMRs//dunnart_d9_vs_sperm.DMRs_hyper0.3.bed")
```





###---DMC Analysis: Day 9 vs Day 10
```{r}
# Identify DMCs
seq_annot <- sequencing.annotate(bsseq_data, methdesign, all.cov = TRUE,
                                contrasts = TRUE, cont.matrix = cont.mat,
                                coef = "d10vsd9", fdr = 0.05) #Your contrast returned no individually significant CpGs. Consider increasing the 'fdr' parameter using changeFDR(), but be warned there is an increased risk of Type I errors.
dmrcate.res <- dmrcate(seq_annot, C = 2, min.cpgs = 1)


# Create data with 0% for both conditions
percentages <- list(
  `20per` = c(hypo = 0, hyper = 0),
  `50per` = c(hypo = 0, hyper = 0)
)

# Modified plotting function to handle zero values
plot_dmc_percentages_zero <- function(hypo_pct, hyper_pct, threshold, filename) {
  df <- data.frame(
    per_of_CpGs = c(hypo_pct, hyper_pct),
    DMC_type = c("Hypomethylated", "Hypermethylated"),
    design = "E10 vs E9"
  )
  
  # Add small offset for visualization when both are zero
  total_pct <- sum(df$per_of_CpGs)
  if (total_pct == 0) {
    df$per_of_CpGs <- c(0.01, 0.01)  # Tiny bars for visualization
    label_text <- "0%"
  } else {
    label_text <- paste0(round(df$per_of_CpGs, 2), "%")
  }
  
  p <- ggplot(df, aes(x = design, y = per_of_CpGs, fill = DMC_type)) +
    geom_col(position = "stack", alpha = 0.8) +
    geom_text(aes(label = "0%"), 
              position = position_stack(vjust = 0.5), 
              color = "black", fontface = "bold", size = 4) +
    labs(title = paste0("DMCs (±", threshold, "%)"),
         subtitle = "Sperm vs Embryonic Day 9",
         y = "Percentage of CpGs", x = NULL, fill = "Direction") +
    scale_y_continuous(limits = c(0, 100), labels = function(x) paste0(x, "%")) +
    scale_fill_manual(values = c("Hypomethylated" = "#2166AC", "Hypermethylated" = "#D73027")) +
    theme_minimal() +
    theme(plot.title = element_text(face = "bold", hjust = 0.5),
          plot.subtitle = element_text(hjust = 0.5),
          axis.text.x = element_blank(),
          legend.position = "bottom") +
    annotate("text", x = 1, y = 50, label = "No significant DMCs detected", 
             size = 5, color = "gray50", fontface = "italic")
  
  ggsave(filename, p, width = 1.5, height = 6, units = "in", dpi = 300)
  return(p)
}

# Generate plots with zero values
setwd("/Users/ksenia/Documents/Lab_Garvan/projects/marsupials/EMseq_final_genome/DMCs_DMRcate/figures/")
p1 <- plot_dmc_percentages_zero(percentages$`20per`["hypo"], percentages$`20per`["hyper"], 
                               20, "DMCs_E9_vs_E10_20pct_threshold_ZERO.pdf")

p2 <- plot_dmc_percentages_zero(percentages$`50per`["hypo"], percentages$`50per`["hyper"], 
                               50, "DMCs_E9_vs_E10_50pct_threshold_ZERO.pdf")

```


###---DMC Analysis: Day 12 vs Day 10
```{r}
library(DMRcate)
library(ggplot2)

# Identify DMCs
seq_annot <- sequencing.annotate(bsseq_data, methdesign, all.cov = TRUE,
                                contrasts = TRUE, cont.matrix = cont.mat,
                                coef = "d12vsd10", fdr = 0.05)
dmrcate.res <- dmrcate(seq_annot, C = 2, min.cpgs = 1)

# Extract all CpGs:
gr <- seq_annot@ranges
# Extract significant DMCs
gr_sig <- seq_annot@ranges[seq_annot@ranges$is.sig == "TRUE"]

# Calculate methylation scores
CpG <- c(bigtable, ignore.mcols=TRUE)
values(CpG) <- as.data.frame(bigtable)[,-c(1:5)]  

col<-seq(1, ncol(mcols(CpG)), by=2)
names <- sub("\\.(C|cov)$", "", colnames(mcols(CpG))[col])
col <- setNames(col, names)


mc_score <- mapply(function(a, b){mcols(CpG)[, a] / mcols(CpG)[, b]}, a = col, b = col+1) 
mc_score<-as.data.frame(mc_score)
mcols(CpG) <- NULL
mcols(CpG) <- cbind(mcols(CpG), mc_score)

# Calculate methylation differences
CpG_sig <- subsetByOverlaps(CpG, gr_sig)
CpG_sig$delta <- (CpG_sig$d12_r1 + CpG_sig$d12_r2)/2 - 
                 (CpG_sig$d10_r1 + CpG_sig$d10_r2)/2

# Filter scaffolds and calculate percentages
puc_lambda <- c("pUC19", "chrLambda")
CpG_filt <- CpG_sig[!seqnames(CpG_sig) %in% puc_lambda]
gr_filt <- gr[!seqnames(gr) %in% puc_lambda]
total_cpgs <- length(gr_filt) #total number of CpGs with min cov of 1 in two samples which are being compared

# Define diff mC thresholds and calculate percentages
calculate_percentages <- function(data, total, thresholds = c(0.2, 0.5)) {
  results <- list()
  for (thresh in thresholds) {
    hypo <- sum(data$delta <= -thresh) / total * 100
    hyper <- sum(data$delta >= thresh) / total * 100
    results[[paste0(thresh * 100, "per")]] <- c(hypo = hypo, hyper = hyper)
  }
  return(results)
}

percentages <- calculate_percentages(as.data.frame(CpG_filt), total_cpgs)

# Create visualization function
plot_dmc_percentages <- function(hypo_pct, hyper_pct, threshold, filename) {
  df <- data.frame(
    per_of_CpGs = c(hypo_pct, hyper_pct),
    DMC_type = c("Hypomethylated", "Hypermethylated"),
    design = "E12 vs E10"
  )
  
  p <- ggplot(df, aes(x = design, y = per_of_CpGs, fill = DMC_type)) +
    geom_col(position = "stack") +
    geom_text(aes(label = paste0(round(per_of_CpGs, 2), "%")), 
              position = position_stack(vjust = 0.5), color = "white", fontface = "bold") +
    labs(title = paste0("DMCs (±", threshold, "%)"),
         subtitle = "E12 vs E10",
         y = "Percentage of CpGs", x = NULL, fill = "Direction") +
    scale_y_continuous(limits = c(0, 100), labels = function(x) paste0(x, "%")) +
    scale_fill_manual(values = c("Hypomethylated" = "#2166AC", "Hypermethylated" = "#D73027")) +
    theme_minimal() +
    theme(plot.title = element_text(face = "bold", hjust = 0.5),
          plot.subtitle = element_text(hjust = 0.5),
          axis.text.x = element_blank(),
          legend.position = "bottom")
  
  ggsave(filename, p, width = 1.5, height = 5, units = "in", dpi = 300)
  return(p)
}

# Generate plots
setwd("/Users/ksenia/Documents/Lab_Garvan/projects/marsupials/EMseq_final_genome/DMCs_DMRcate/figures/")
p1 <- plot_dmc_percentages(percentages$`20per`["hypo"], percentages$`20per`["hyper"], 
                          20, "DMCs_E12_vs_E10_20pct_threshold.pdf")
p2 <- plot_dmc_percentages(percentages$`50per`["hypo"], percentages$`50per`["hyper"], 
                          50, "DMCs_E12_vs_E10_50pct_threshold.pdf")


# Save results
saveRDS(percentages, "/Users/ksenia/Documents/Lab_Garvan/projects/marsupials/EMseq_final_genome/DMCs_DMRcate/source_data/DMC_percentages_E12_vs_E10.rds")
saveRDS(as.data.frame(CpG_filt), "/Users/ksenia/Documents/Lab_Garvan/projects/marsupials/EMseq_final_genome/DMCs_DMRcate/source_data/DMC_mC_score_E12_vs_E10_sign.rds")

# Export BED files
setwd("/Users/ksenia/Documents/Lab_Garvan/projects/marsupials/EMseq_final_genome/DMCs_DMRcate/source_data/")
rtracklayer::export(gr_filt, "E12_vs_E10_background.bed")
rtracklayer::export(gr_sig, "E12_vs_E10_significant_DMCs.bed")
rtracklayer::export(CpG_filt[CpG_filt$delta <= -0.2], "E12_vs_E10_hypomethylated_20pct.bed")
rtracklayer::export(CpG_filt[CpG_filt$delta >= 0.2], "E12_vs_E10_hypermethylated_20pct.bed")
```

###---DMC Analysis: Day 13 vs Day 12
```{r}
library(DMRcate)
library(ggplot2)

# Identify DMCs
seq_annot <- sequencing.annotate(bsseq_data, methdesign, all.cov = TRUE,
                                contrasts = TRUE, cont.matrix = cont.mat,
                                coef = "d13vsd12", fdr = 0.05)
dmrcate.res <- dmrcate(seq_annot, C = 2, min.cpgs = 1)

# Extract all CpGs:
gr <- seq_annot@ranges
# Extract significant DMCs
gr_sig <- seq_annot@ranges[seq_annot@ranges$is.sig == "TRUE"]

# Calculate methylation scores
CpG <- c(bigtable, ignore.mcols=TRUE)
values(CpG) <- as.data.frame(bigtable)[,-c(1:5)]  

col<-seq(1, ncol(mcols(CpG)), by=2)
names <- sub("\\.(C|cov)$", "", colnames(mcols(CpG))[col])
col <- setNames(col, names)


mc_score <- mapply(function(a, b){mcols(CpG)[, a] / mcols(CpG)[, b]}, a = col, b = col+1) 
mc_score<-as.data.frame(mc_score)
mcols(CpG) <- NULL
mcols(CpG) <- cbind(mcols(CpG), mc_score)

# Calculate methylation differences
CpG_sig <- subsetByOverlaps(CpG, gr_sig)
CpG_sig$delta <- (CpG_sig$d13_rep1 + CpG_sig$d13_rep2)/2 - 
                 (CpG_sig$d12_rep1 + CpG_sig$d12_rep2)/2

# Filter scaffolds and calculate percentages
puc_lambda <- c("pUC19", "chrLambda")
CpG_filt <- CpG_sig[!seqnames(CpG_sig) %in% puc_lambda]
gr_filt <- gr[!seqnames(gr) %in% puc_lambda]
total_cpgs <- length(gr_filt) #total number of CpGs with min cov of 1 in two samples which are being compared

# Define diff mC thresholds and calculate percentages
calculate_percentages <- function(data, total, thresholds = c(0.2, 0.5)) {
  results <- list()
  for (thresh in thresholds) {
    hypo <- sum(data$delta <= -thresh) / total * 100
    hyper <- sum(data$delta >= thresh) / total * 100
    results[[paste0(thresh * 100, "per")]] <- c(hypo = hypo, hyper = hyper)
  }
  return(results)
}

percentages <- calculate_percentages(as.data.frame(CpG_filt), total_cpgs)

# Create visualization function
plot_dmc_percentages <- function(hypo_pct, hyper_pct, threshold, filename) {
  df <- data.frame(
    per_of_CpGs = c(hypo_pct, hyper_pct),
    DMC_type = c("Hypomethylated", "Hypermethylated"),
    design = "E13 vs E12"
  )
  
  p <- ggplot(df, aes(x = design, y = per_of_CpGs, fill = DMC_type)) +
    geom_col(position = "stack") +
    geom_text(aes(label = paste0(round(per_of_CpGs, 2), "%")), 
              position = position_stack(vjust = 0.5), color = "white", fontface = "bold") +
    labs(title = paste0("DMCs (±", threshold, "%)"),
         subtitle = "E13 vs E12",
         y = "Percentage of CpGs", x = NULL, fill = "Direction") +
    scale_y_continuous(limits = c(0, 100), labels = function(x) paste0(x, "%")) +
    scale_fill_manual(values = c("Hypomethylated" = "#2166AC", "Hypermethylated" = "#D73027")) +
    theme_minimal() +
    theme(plot.title = element_text(face = "bold", hjust = 0.5),
          plot.subtitle = element_text(hjust = 0.5),
          axis.text.x = element_blank(),
          legend.position = "bottom")
  
  ggsave(filename, p, width = 1.5, height = 5, units = "in", dpi = 300)
  return(p)
}

# Generate plots
setwd("/Users/ksenia/Documents/Lab_Garvan/projects/marsupials/EMseq_final_genome/DMCs_DMRcate/figures/")
p1 <- plot_dmc_percentages(percentages$`20per`["hypo"], percentages$`20per`["hyper"], 
                          20, "DMCs_E13_vs_E12_20pct_threshold.pdf")
p2 <- plot_dmc_percentages(percentages$`50per`["hypo"], percentages$`50per`["hyper"], 
                          50, "DMCs_E13_vs_E12_50pct_threshold.pdf")


# Save results
saveRDS(percentages, "/Users/ksenia/Documents/Lab_Garvan/projects/marsupials/EMseq_final_genome/DMCs_DMRcate/source_data/DMC_percentages_E13_vs_E12.rds")
saveRDS(as.data.frame(CpG_filt), "/Users/ksenia/Documents/Lab_Garvan/projects/marsupials/EMseq_final_genome/DMCs_DMRcate/source_data/DMC_mC_score_E13_vs_E12_sign.rds")
e13_e12<- readRDS("/Users/ksenia/Documents/Lab_Garvan/projects/marsupials/EMseq_final_genome/DMCs_DMRcate/source_data/DMC_mC_score_E13_vs_E12_sign.rds")

# Export BED files
setwd("/Users/ksenia/Documents/Lab_Garvan/projects/marsupials/EMseq_final_genome/DMCs_DMRcate/source_data/")
rtracklayer::export(gr_filt, "E13_vs_E12_background.bed")
rtracklayer::export(gr_sig, "E13_vs_E12_significant_DMCs.bed")
rtracklayer::export(CpG_filt[CpG_filt$delta <= -0.2], "E13_vs_E12_hypomethylated_20pct.bed")
rtracklayer::export(CpG_filt[CpG_filt$delta >= 0.2], "E13_vs_E12_hypermethylated_20pct.bed")
```

###---DMC Analysis: Liver vs Day 13
```{r}
library(DMRcate)
library(ggplot2)

# Identify DMCs
seq_annot <- sequencing.annotate(bsseq_data, methdesign, all.cov = TRUE,
                                contrasts = TRUE, cont.matrix = cont.mat,
                                coef = "livervsd13", fdr = 0.05)
dmrcate.res <- dmrcate(seq_annot, C = 2, min.cpgs = 1)

# Extract significant DMCs
gr_sig <- seq_annot@ranges[seq_annot@ranges$is.sig == "TRUE"]

# Calculate methylation scores
CpG <- c(bigtable, ignore.mcols=TRUE)
values(CpG) <- as.data.frame(bigtable)[,-c(1:5)]  

col<-seq(1, ncol(mcols(CpG)), by=2)
names <- sub("\\.(C|cov)$", "", colnames(mcols(CpG))[col])
col <- setNames(col, names)


mc_score <- mapply(function(a, b){mcols(CpG)[, a] / mcols(CpG)[, b]}, a = col, b = col+1) 
mc_score<-as.data.frame(mc_score)
mcols(CpG) <- NULL
mcols(CpG) <- cbind(mcols(CpG), mc_score)

# Calculate methylation differences
CpG_sig <- subsetByOverlaps(CpG, gr_sig)
CpG_sig$delta <- (CpG_sig$liver_r1 + CpG_sig$liver_r2)/2 - 
                 (CpG_sig$d13_r1 + CpG_sig$d13_r2)/2

# Filter scaffolds and calculate percentages
puc_lambda <- c("pUC19", "chrLambda")
CpG_filt <- CpG_sig[!seqnames(CpG_sig) %in% puc_lambda]
gr_filt <- gr[!seqnames(gr) %in% puc_lambda]
total_cpgs <- length(gr_filt) #total number of CpGs with min cov of 1 in two samples which are being compared

# Define diff mC thresholds and calculate percentages
calculate_percentages <- function(data, total, thresholds = c(0.2, 0.5)) {
  results <- list()
  for (thresh in thresholds) {
    hypo <- sum(data$delta <= -thresh) / total * 100
    hyper <- sum(data$delta >= thresh) / total * 100
    results[[paste0(thresh * 100, "per")]] <- c(hypo = hypo, hyper = hyper)
  }
  return(results)
}

percentages <- calculate_percentages(as.data.frame(CpG_filt), total_cpgs)

# Create visualization function
plot_dmc_percentages <- function(hypo_pct, hyper_pct, threshold, filename) {
  df <- data.frame(
    per_of_CpGs = c(hypo_pct, hyper_pct),
    DMC_type = c("Hypomethylated", "Hypermethylated"),
    design = "liver vs E13"
  )
  
  p <- ggplot(df, aes(x = design, y = per_of_CpGs, fill = DMC_type)) +
    geom_col(position = "stack") +
    geom_text(aes(label = paste0(round(per_of_CpGs, 2), "%")), 
              position = position_stack(vjust = 0.5), color = "white", fontface = "bold") +
    labs(title = paste0("DMCs (±", threshold, "%)"),
         subtitle = "liver vs E13",
         y = "Percentage of CpGs", x = NULL, fill = "Direction") +
    scale_y_continuous(limits = c(0, 100), labels = function(x) paste0(x, "%")) +
    scale_fill_manual(values = c("Hypomethylated" = "#2166AC", "Hypermethylated" = "#D73027")) +
    theme_minimal() +
    theme(plot.title = element_text(face = "bold", hjust = 0.5),
          plot.subtitle = element_text(hjust = 0.5),
          axis.text.x = element_blank(),
          legend.position = "bottom")
  
  ggsave(filename, p, width = 1.5, height = 5, units = "in", dpi = 300)
  return(p)
}

# Generate plots
setwd("/Users/ksenia/Documents/Lab_Garvan/projects/marsupials/EMseq_final_genome/DMCs_DMRcate/figures/")
p1 <- plot_dmc_percentages(percentages$`20per`["hypo"], percentages$`20per`["hyper"], 
                          20, "DMCs_liver_vs_E13_20pct_threshold.pdf")
p2 <- plot_dmc_percentages(percentages$`50per`["hypo"], percentages$`50per`["hyper"], 
                          50, "DMCs_liver_vs_E13_50pct_threshold.pdf")


# Save results
saveRDS(percentages, "/Users/ksenia/Documents/Lab_Garvan/projects/marsupials/EMseq_final_genome/DMCs_DMRcate/source_data/DMC_percentages_liver_vs_E13.rds")
saveRDS(as.data.frame(CpG_filt), "/Users/ksenia/Documents/Lab_Garvan/projects/marsupials/EMseq_final_genome/DMCs_DMRcate/source_data/DMC_mC_score_liver_vs_E13_sign.rds")

# Export BED files
setwd("/Users/ksenia/Documents/Lab_Garvan/projects/marsupials/EMseq_final_genome/DMCs_DMRcate/source_data/")
rtracklayer::export(gr_filt, "liver_vs_E13_background.bed")
rtracklayer::export(gr_sig, "liver_vs_E13_significant_DMCs.bed")
rtracklayer::export(CpG_filt[CpG_filt$delta <= -0.2], "liver_vs_E13_hypomethylated_20pct.bed")
rtracklayer::export(CpG_filt[CpG_filt$delta >= 0.2], "liver_vs_E13_hypermethylated_20pct.bed")
```

###---ALLUVIAL PLOTS
```{r}
bkgd <- import("/Users/ksenia/Documents/Lab_Garvan/projects/marsupials/EMseq_final_genome/DMCs_DMRcate/source_data/liver_vs_E13_background.bed")
bkgd$id <- paste0(seqnames(bkgd), sep="_", start(bkgd))

# Get all BED file paths
bed_dir <- "/Users/ksenia/Documents/Lab_Garvan/projects/marsupials/EMseq_final_genome/DMCs_DMRcate/source_data/"
bed_files <- list.files(bed_dir, pattern = "20pct.bed$", full.names = TRUE)

# Import all files into a named list
bed_data <- lapply(bed_files, import)
names(bed_data) <- gsub("/Users/ksenia/Documents/Lab_Garvan/projects/marsupials/EMseq_final_genome/DMCs_DMRcate/source_data", "", gsub("_20pct.bed", "", bed_files))

#Add an 'id' column to each bed file
library(S4Vectors)
bed_data <- lapply(bed_data, function(gr) {
  if(length(gr) > 0) {
    mcols(gr) <- DataFrame(mcols(gr), 
                          id = paste0(as.character(seqnames(gr)), "_", start(gr)))
  }
  return(gr)
})

# Extract comparison names from bed_data (remove _hypermethylated/_hypomethylated suffixes)
comparison_names <- unique(gsub("_(hypermethylated|hypomethylated)", "", names(bed_data)))

# Function to annotate background with DMC status
annotate_dmc_status <- function(bkgd, bed_data_list, comparisons) {
  
  for (comp in comparisons) {
    # Get hypomethylated and hypermethylated datasets for this comparison
    hypo_name <- paste0(comp, "_hypomethylated")
    hyper_name <- paste0(comp, "_hypermethylated")
    
    # Initialize column with "NC" (No Change)
    mcols(bkgd)[[comp]] <- "NC"
    
    # Check if datasets exist in the list
    if (hypo_name %in% names(bed_data_list)) {
      hypo_ids <- bed_data_list[[hypo_name]]$id
      mcols(bkgd)[[comp]][bkgd$id %in% hypo_ids] <- "hypo"
    }
    
    if (hyper_name %in% names(bed_data_list)) {
      hyper_ids <- bed_data_list[[hyper_name]]$id
      mcols(bkgd)[[comp]][bkgd$id %in% hyper_ids] <- "hyper"
    }
    
    cat("Added column", comp, "with", 
        sum(mcols(bkgd)[[comp]] == "hypo"), "hypo,", 
        sum(mcols(bkgd)[[comp]] == "hyper"), "hyper,", 
        sum(mcols(bkgd)[[comp]] == "NC"), "NC\n")
  }
  
  return(bkgd)
}

# Apply the annotation
bkgd_annotated <- annotate_dmc_status(bkgd, bed_data, comparison_names)
bkgd_annotated_df <- as.data.frame(bkgd_annotated)
saveRDS(bkgd_annotated_df, "/Users/ksenia/Documents/Lab_Garvan/projects/marsupials/EMseq_final_genome/DMCs_DMRcate/source_data/DMCs_status_alluvial_plot.rds")

all <- bkgd_annotated_df[, c(8:ncol(bkgd_annotated_df))]
colnames(all) <- c("id", "E12_vs_E10", "E13_vs_E12", "liver_vs_E13", "sperm_vs_E9")

#add E10_vs_E9 column will all NC
all$E10_vs_E9 <- "NC"
all <- all[,c(1,5,6,2,3,4)]
all$id <- paste(all$sperm_vs_E9, all$E10_vs_E9, all$E12_vs_E10, all$E13_vs_E12, all$liver_vs_E13, sep="_")

freq <- as.data.frame(table(all$id))
freq
x<-as.data.frame(do.call(rbind, strsplit(as.character(freq$Var1), "_")))
x<-cbind(x, freq$Freq)
colnames(x) <- c("sperm_vs_E9", "E10_vs_E9", "E12_vs_E10", "E13_vs_E12", "liver_vs_E13", "freq") #nrow(x) = 20
x$number <- c(1:nrow(x))
x.m <-melt(x, measure.vars=c("sperm_vs_E9", "E10_vs_E9", "E12_vs_E10", "E13_vs_E12", "liver_vs_E13"))
head(x.m)


library(ggalluvial)
colors <- c("hypo" = "#2166AC", "hyper" = "#D73027", "NC" = "#808080")
setwd("/Users/ksenia/Documents/Lab_Garvan/projects/marsupials/EMseq_final_genome/DMCs_DMRcate/figures/alluvial/")
pdf("mC_alluvial_DMCs_DMRcate.pdf", useDingbats=FALSE, width=10, height=8)
print(ggplot(x, aes(axis1 = sperm_vs_E9, axis2 = E10_vs_E9, axis3 = E12_vs_E10, 
                   axis4 = E13_vs_E12, axis5 = liver_vs_E13, y = freq)) +
  scale_x_discrete(limits = c("sperm_vs_E9", "E10_vs_E9", "E12_vs_E10", "E13_vs_E12", "liver_vs_E13"),
                   labels = c("Sperm vs E9", "E9 vs E10", "E10 vs E12", "E12 vs E13", "E13 vs Liver")) +
  geom_alluvium(aes(fill = sperm_vs_E9), alpha = 0.8, curve_type = "cubic") +
  geom_stratum(aes(fill = after_stat(stratum)), alpha = 0.7, color = "white", size = 0.5) +
  geom_text(stat = "stratum", aes(label = after_stat(stratum)), 
            size = 3, fontface = "bold", color = "white") +
  scale_fill_manual(values = colors, name = "Methylation\nStatus") +
  labs(title = "CpG Methylation Dynamics Across Development",
       subtitle = "Trajectory of differentially methylated CpGs from sperm through embryogenesis to liver",
       x = "Developmental Stage Comparisons", y = "Number of CpGs") +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 16, face = "bold", hjust = 0.5),
    plot.subtitle = element_text(size = 12, hjust = 0.5, color = "gray40"),
    axis.text.x = element_text(angle = 45, hjust = 1, size = 10),
    axis.text.y = element_text(size = 10),
    axis.title = element_text(size = 12, face = "bold"),
    legend.title = element_text(size = 11, face = "bold"),
    legend.text = element_text(size = 10),
    panel.grid = element_blank(),
    plot.margin = margin(20, 20, 20, 20)
  ))
dev.off()
```

